name: Deploy Website
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Set up env
        run: pip install -r requirements.txt
      - name: Build static files
        run: mkdocs build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: 'site'
      - id: deployment
        uses: actions/deploy-pages@v4